
drop table if exists history cascade;
drop table if exists users cascade;
drop table if exists currency_rate cascade;
DROP INDEX if exists date_code_rate_id_index;
create table currency_rate (
                               id int8 not null,
                               base varchar(255),
                               code varchar(255),
                               rate numeric(19, 2),
                               date timestamp,
                               primary key (id)
);
create table history (
                         id int8 generated by default as identity,
                         currency_from varchar(255),
                         currency_to varchar(255),
                         operation_time timestamp,
                         result float8,
                         amount float8,
                         user_id int8,
                         primary key (id)
);
create table users (
                       id int8 generated by default as identity,
                       email varchar(255) not null,
                       first_name varchar(20) not null,
                       last_name varchar(20) not null,
                       password varchar(255) not null,
                       registration_time timestamp,
                       username varchar(255),
                       primary key (id)
);

CREATE UNIQUE INDEX date_code_rate_id_index ON currency_rate (date, code, rate, id);

alter table if exists users drop constraint if exists UK_6dotkott2kjsp8vw4d0m25fb7;

alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);

alter table if exists history add constraint FKq4kh99ws9lhtls5i3o73gw30t foreign key (user_id) references users;

insert
into
    users
(email, first_name, last_name, password, registration_time, username, id)
values
    (  'user@gmail.com', 'Donald', 'Trump',
       '$2a$10$qpUZgb//qeWDxi68nubWT.k4/Rl0VqNdXs/glTyElQdcf8i/aOEbq' , '2021-10-30 01:13:49.37946','Donald Trump', '1')
